#!/usr/bin/env bash
set -euo pipefail

sqlplus -s / as sysdba <<SQL
ALTER SESSION SET CONTAINER=ORCLPDB1;
CREATE USER ${ITZ_DB_USER} IDENTIFIED BY "${ITZ_DB_PASSWORD}";
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO ${ITZ_DB_USER};
ALTER USER ${ITZ_DB_USER} QUOTA UNLIMITED ON USERS;
SQL
